### PR TITLE
SQL query Improvements

### PR DESCRIPTION
**Pull request by CGDEV998**
- new watch service to return media based on user
- updated SQL statements to accept a username instead of a user id
- Updated router promise handling and page rendering
- Improved database access to user for querying data
- Connection string not working, fixed with a different connection method however it is unsafe as plain text in the code base
- Profile page now renders all movies in the watched and to watch lists

### CODE REVIEW

**Review by aaron-goshine — COMMENTED** [review]
don't check in the the .envrc file

**Comment by aaron-goshine** [comment]
Looks goods

**Review by william-eyre — APPROVED** [review]
Looks good to me

**Comment by aaron-goshine** [comment]
looks good

**Pull request merged**
